const app=document.querySelector('#app');
const accountNav=document.querySelector('#account-nav');
const toastEl=document.querySelector('#toast');
let session=null,catalog=null,timerId=null,saveId=null;
const h=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const jsonHeaders={'content-type':'application/json'};
async function request(path,options={}){const response=await fetch(path,{credentials:'same-origin',...options,headers:{...(options.body?jsonHeaders:{}),...(options.headers||{})}});let data={};try{data=await response.json()}catch{}if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data;}
function toast(message,error=false){toastEl.textContent=message;toastEl.className=`toast show${error?' error':''}`;setTimeout(()=>toastEl.className='toast',3500)}
function navigate(path){history.pushState({},'',path);window.scrollTo({top:0,left:0});render();}
function loading(){app.innerHTML='<div class="route-loading"><span></span><p>Loading…</p></div>'}
function updateNav(){accountNav.innerHTML=session?`<a class="button ghost small" href="/dashboard" data-link>${h(session.user.handle)}</a><button class="button small" data-action="logout">Sign out</button>`:'<a class="button ghost small" href="/login" data-link>Sign in</a><a class="button small" href="/join" data-link>Join beta</a>'}
async function loadSession(){try{session=await request('/api/me')}catch{session=null}updateNav()}
async function getCatalog(){if(!catalog)catalog=(await request('/api/challenges')).challenges;return catalog}
function page(title,body){document.title=`${title} — VibeScore`;document.body.classList.remove('in-workspace');document.querySelector('.site-header').hidden=false;document.querySelector('.site-footer').hidden=false;app.innerHTML=body;app.focus({preventScroll:true})}
function workPage(body){document.title='Challenge — VibeScore';document.body.classList.add('in-workspace');document.querySelector('.site-header').hidden=true;document.querySelector('.site-footer').hidden=true;app.innerHTML=body}
function metric(label,value){return `<div class="metric-line"><span>${h(label)}</span><div class="bar"><i style="--value:${Number(value)}%"></i></div><b>${Number(value)}</b></div>`}

function home(){page('Build better with AI',`<div class="shell"><section class="hero"><div class="hero-copy"><div class="eyebrow">The AI builder skill layer</div><h1>Build with AI.<br><span class="gradient-text">Prove you’re good at it.</span></h1><p>VibeScore turns real coding-agent work and controlled challenges into useful coaching, measurable progress, and a profile you can share.</p><div class="hero-actions"><a class="button" href="/join" data-link>Get your VibeScore →</a><a class="button ghost" href="/practice" data-link>Try a skill drill</a></div><div class="trust-row"><span>Raw prompts stay local</span><span>Transparent evidence</span><span>Public by choice</span></div></div><div class="score-preview" aria-label="Example VibeScore profile"><div class="score-orbit"></div><div class="score-card"><div class="score-main"><div class="score-number">1742 <small>± 82</small></div><div class="rank-pill">TOP 12%</div></div><div class="mini-metrics">${metric('Direction',87)}${metric('Craft',76)}${metric('Efficiency',81)}${metric('Shipping',72)}</div></div></div></section><section class="section"><div class="eyebrow">Two paths, one skill profile</div><h2 class="section-title">Measure your work.<br>Sharpen your process.</h2><p class="section-intro">Passive workflow evidence reveals your habits. Controlled practice gives you a fair place to improve and prove them.</p><div class="path-grid"><article class="card path-card"><span class="index">01 · REAL WORK</span><h3>Connect your coding-agent history</h3><p>Run the local MCP on a project you choose. It reduces Claude Code and Codex sessions to private numeric signals, then shows where your workflow helps or hurts.</p><a class="button ghost" href="/privacy" data-link>How private analysis works →</a></article><article class="card path-card"><span class="index">02 · CONTROLLED PRACTICE</span><h3>Train inside an AI-assisted arena</h3><p>Practise framing, context, debugging, verification, review, and efficiency. Take timed coding rounds with an assistant and objective tests.</p><a class="button ghost" href="/practice" data-link>Explore the arena →</a></article></div></section><section class="section"><div class="eyebrow">The loop</div><h2 class="section-title">Evidence that helps you improve.</h2><div class="feature-grid"><article class="card feature-card"><div class="icon-box">01</div><h3>Observe</h3><p>Private local telemetry highlights correction loops, context quality, tool use, verification, and delivery signals.</p></article><article class="card feature-card"><div class="icon-box">02</div><h3>Practise</h3><p>Your weakest dimension maps to focused drills and interview rounds with immediate, honest feedback.</p></article><article class="card feature-card"><div class="icon-box">03</div><h3>Prove</h3><p>Controlled attempts create a separate assessed rating for your profile and the global beta leaderboard.</p></article></div></section></div>`)}

async function practice(filter='all'){loading();const items=await getCatalog();const shown=filter==='all'?items:items.filter(x=>x.kind===filter);page('Practice',`<div class="shell"><header class="page-head"><div class="eyebrow">Skill arena</div><h1>Practice the process,<br>not trivia.</h1><p>Short drills strengthen how you direct and review AI. Timed coding rounds test whether you can use assistance and still ship correct work.</p></header><div class="tabs"><button class="tab ${filter==='all'?'active':''}" data-filter="all">All ${items.length}</button><button class="tab ${filter==='drill'?'active':''}" data-filter="drill">Drills ${items.filter(x=>x.kind==='drill').length}</button><button class="tab ${filter==='interview'?'active':''}" data-filter="interview">Interview rounds ${items.filter(x=>x.kind==='interview').length}</button></div><div class="challenge-grid">${shown.map(challengeCard).join('')}</div></div>`)}
function challengeCard(c){return `<article class="card challenge-card"><div class="challenge-meta"><span class="skill">${h(c.skill)}</span><span>${h(c.difficulty)} · ${c.minutes} min</span></div><h3>${h(c.title)}</h3><p>${h(c.summary)}</p><a class="button ghost wide" href="/challenge/${encodeURIComponent(c.id)}" data-link>${c.kind==='drill'?'Open drill':'View interview'} →</a></article>`}
async function challengeDetail(id){loading();const {challenge:c}=await request(`/api/challenges/${encodeURIComponent(id)}`);page(c.title,`<div class="shell"><div class="challenge-detail"><article class="challenge-body"><div class="eyebrow">${h(c.kind)} · ${h(c.skill)}</div><h1>${h(c.title)}</h1><p>${h(c.summary)}</p><h2>Your brief</h2><p>${h(c.prompt)}</p><h2>What good work includes</h2><ul class="requirements">${c.requirements.map(x=>`<li>${h(x)}</li>`).join('')}</ul></article><aside class="card side-panel"><dl><div><dt>Difficulty</dt><dd>${h(c.difficulty)}</dd></div><div><dt>Time</dt><dd>${c.minutes} min</dd></div><div><dt>Skill</dt><dd>${h(c.skill)}</dd></div><div><dt>Format</dt><dd>${h(c.kind)}</dd></div></dl><button class="button wide" data-start="${h(c.id)}" data-mode="practice">Start practice</button>${c.kind==='interview'?`<button class="button ghost wide" style="margin-top:.6rem" data-start="${h(c.id)}" data-mode="rated">Start rated round</button>`:''}<p class="form-note">Rated interview timers begin immediately. Your first completed rated attempt on a task is eligible for the beta rating.</p></aside></div></div>`)}

function authPage(kind){const join=kind==='join',recover=kind==='recover';page(join?'Join the beta':recover?'Recover access':'Sign in',`<div class="auth-wrap"><div class="card auth-card"><div class="eyebrow">${join?'Create your profile':recover?'Account recovery':'Welcome back'}</div><h1>${join?'Start building better.':recover?'Use your recovery code.':'Sign in to VibeScore.'}</h1><p>${join?'Your profile stays private until you publish it.':recover?'Successful recovery replaces your old sessions and code.':'Continue your drills, attempts, and progress.'}</p><form class="form" id="auth-form" data-kind="${kind}"><div class="field"><label for="handle">Handle</label><input id="handle" name="handle" required minlength="2" maxlength="24" pattern="[a-z0-9][a-z0-9_-]+" autocomplete="username" placeholder="hokie_builder"></div>${recover?'<div class="field"><label for="recovery">Recovery code</label><input id="recovery" name="recoveryCode" required autocomplete="off"></div>':''}<div class="field"><label for="password">${recover?'New password':'Password'}</label><input id="password" name="${recover?'newPassword':'password'}" type="password" required minlength="10" autocomplete="${join?'new-password':'current-password'}"></div><button class="button wide" type="submit">${join?'Create account':recover?'Recover account':'Sign in'} →</button><p class="form-note">${join?'Already have an account? <a href="/login" data-link>Sign in</a>':recover?'Remembered it? <a href="/login" data-link>Sign in</a>':'Lost access? <a href="/recover" data-link>Use your recovery code</a>'}</p></form></div></div>`)}
function showRecovery(code){page('Save recovery code',`<div class="auth-wrap"><div class="card auth-card"><div class="eyebrow">One important step</div><h1>Save this code.</h1><p>It is the only way to recover your account. We store only a one-way hash and cannot show it again.</p><div class="recovery-box"><code>${h(code)}</code></div><button class="button wide" style="margin-top:1rem" data-action="copy-recovery" data-code="${h(code)}">Copy recovery code</button><a class="button ghost wide" style="margin-top:.6rem" href="/dashboard" data-link>I saved it — continue</a></div></div>`)}

async function dashboard(){if(!session)return navigate('/login');loading();session=await request('/api/me');updateNav();const s=session.summary,a=session.attempts;page('Dashboard',`<div class="shell"><header class="page-head"><div class="eyebrow">Your command center</div><h1>Welcome back,<br>${h(session.user.handle)}.</h1><p>Keep the loop moving: practise a weak skill, finish a controlled round, then compare the result with your real workflow.</p></header><div class="stats-grid"><div class="card stat-card"><strong>${s.rating??'—'}</strong><span>Challenge rating</span></div><div class="card stat-card"><strong>${s.ratedTasks}</strong><span>Rated tasks</span></div><div class="card stat-card"><strong>${s.completed}</strong><span>Completed attempts</span></div><div class="card stat-card"><strong>${session.user.isPublic?'Live':'Private'}</strong><span>Profile visibility</span></div></div><div class="dashboard-grid"><section class="card"><div class="challenge-meta"><span>Recent activity</span><a href="/practice" data-link>Find a challenge →</a></div><div class="activity">${a.length?a.slice(0,8).map(x=>`<a class="activity-row" href="/attempt/${h(x.id)}" data-link><span><b>${h(x.challengeId.replaceAll('-',' '))}</b><br><small class="muted">${new Date(x.startedAt).toLocaleDateString()} · ${h(x.mode)}</small></span><span class="status-chip ${h(x.status)}">${h(x.status)}</span></a>`).join(''):'<div class="empty">No attempts yet. Your first drill takes about seven minutes.</div>'}</div></section><aside class="card"><div class="eyebrow">Next move</div><h2>${s.ratedTasks<2?'Establish your beta rating':'Strengthen your range'}</h2><p class="muted">${s.ratedTasks<2?'Complete two different rated interview tasks to appear on the public challenge leaderboard.':'Try a task in a different skill dimension or connect your real-work report through the MCP.'}</p><a class="button wide" href="/practice" data-link>Choose a challenge</a><a class="button ghost wide" style="margin-top:.6rem" href="/settings" data-link>Profile settings</a></aside></div></div>`)}

async function attemptPage(id){if(!session)return navigate('/login');loading();const data=await request(`/api/attempts/${encodeURIComponent(id)}`),a=data.attempt,c=data.challenge;if(a.status==='submitted')return resultPage(a,c);if(c.kind==='drill')return drillAttempt(a,c);return interviewAttempt(a,c,data.messages||[])}
function timer(deadline){clearInterval(timerId);const el=document.querySelector('#timer');if(!el)return;const update=()=>{const seconds=Math.max(0,Math.floor((Date.parse(deadline)-Date.now())/1000));el.textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;if(!seconds)clearInterval(timerId)};update();timerId=setInterval(update,1000)}
function drillAttempt(a,c){workPage(`<div class="workspace"><div class="work-top"><a href="/challenge/${h(c.id)}" data-link>← Exit</a><h1>${h(c.title)}</h1><span class="status-chip">${h(a.mode)}</span><span class="timer" id="timer"></span></div><div class="drill-workspace"><div class="eyebrow">${h(c.skill)} drill</div><h2>${h(c.prompt)}</h2><ul class="requirements">${c.requirements.map(x=>`<li>${h(x)}</li>`).join('')}</ul><form id="drill-form"><div class="field"><label for="answer">Your instruction to the AI</label><textarea class="drill-answer" id="answer" name="answer" placeholder="Be specific about evidence, constraints, and success checks…">${h(a.answer)}</textarea></div><div class="hero-actions"><button class="button" type="submit">Check my response →</button><button class="button ghost" type="button" data-action="save-draft">Save draft</button></div></form></div></div>`);timer(a.deadline)}
function interviewAttempt(a,c,messages){workPage(`<div class="workspace"><div class="work-top"><a href="/challenge/${h(c.id)}" data-link>← Exit</a><h1>${h(c.title)}</h1><span class="status-chip">${h(a.mode)}</span><span class="timer" id="timer"></span></div><div class="work-grid"><section class="work-pane prompt-pane"><div class="pane-head">Brief</div><div class="content"><div class="eyebrow">${h(c.skill)}</div><h2>${h(c.prompt)}</h2><ul class="requirements">${c.requirements.map(x=>`<li>${h(x)}</li>`).join('')}</ul>${c.examples?.length?`<h3>Examples</h3>${c.examples.map(x=>`<div class="card"><code>${h(JSON.stringify(x.input))} → ${h(JSON.stringify(x.output))}</code><p>${h(x.explanation)}</p></div>`).join('')}`:''}<div id="run-results" class="results"></div></div></section><section class="work-pane"><div class="pane-head">Solution · JavaScript</div><textarea id="code-editor" class="code-editor" spellcheck="false" aria-label="Code editor">${h(a.code||c.starterCode)}</textarea><div class="editor-actions"><button class="button ghost small" data-action="run-code">Run tests</button><button class="button small" data-action="submit-code">Submit solution</button></div></section><aside class="work-pane assistant-pane"><div class="pane-head">Gemini interview coach</div><div class="chat" id="chat">${messages.length?messages.map(m=>`<div class="message ${h(m.role)}">${h(m.content)}</div>`).join(''):'<div class="message assistant">I can help you clarify the task, reason through tradeoffs, debug, and verify. I won’t hand you a complete solution.</div>'}</div><form class="chat-form" id="chat-form"><textarea name="message" aria-label="Message the interview coach" placeholder="Ask for a hint…"></textarea><button class="button small" type="submit">Send</button></form></aside></div></div>`);timer(a.deadline);const editor=document.querySelector('#code-editor');editor.addEventListener('input',()=>{clearTimeout(saveId);saveId=setTimeout(()=>saveAttempt(a.id,{code:editor.value},false),1200)})}
async function saveAttempt(id,payload,notify=true){await request(`/api/attempts/${id}`,{method:'PATCH',body:JSON.stringify(payload)});if(notify)toast('Draft saved')}
function resultPage(a,c){const r=a.result||{},score=r.totalScore??r.score??0;page('Attempt result',`<div class="shell"><section class="card result-hero"><div class="eyebrow" style="justify-content:center">Attempt complete</div><div class="result-score">${h(score)}${r.totalScore!==undefined||r.maxScore===100?'<small>%</small>':''}</div><h1>${h(c.title)}</h1><p class="muted">${h(r.notice||r.ratingNote||'Your result has been saved.')}</p><div class="hero-actions" style="justify-content:center"><a class="button" href="/practice" data-link>Keep practising</a><a class="button ghost" href="/dashboard" data-link>View dashboard</a></div></section>${r.criteria?`<section class="section"><h2 class="section-title">Rubric feedback</h2><div class="feature-grid">${r.criteria.map(x=>`<article class="card"><div class="challenge-meta"><span>${h(x.label)}</span><b>${x.pointsEarned}/${x.pointsPossible}</b></div><p class="muted">${h(x.feedback)}</p></article>`).join('')}</div></section>`:''}${r.visibleTests?`<section class="section"><h2 class="section-title">Test evidence</h2><div class="card">${r.visibleTests.map(x=>`<div class="test-row"><span>${h(x.label)}</span><b class="${x.passed?'pass':'fail'}">${x.passed?'Passed':'Failed'}</b></div>`).join('')}<p class="muted">Hidden tests passed: ${r.hiddenTestsPassed}/${r.hiddenTestsTotal}</p></div></section>`:''}</div>`)}

async function leaderboard(type='challenge'){loading();const data=await request(`/api/leaderboard?type=${type}`);page('Leaderboard',`<div class="shell"><header class="page-head"><div class="eyebrow">Public beta ladder</div><h1>Skill earns the rank.</h1><p>Challenge ratings use controlled first attempts. Imported workflow scores remain separate and provisional.</p></header><div class="tabs"><button class="tab ${type==='challenge'?'active':''}" data-board="challenge">Challenge rating</button><button class="tab ${type==='workflow'?'active':''}" data-board="workflow">Workflow score</button></div><div class="card leaderboard"><div class="leader-row head"><span>Rank</span><span>Builder</span><span>Score</span><span>Evidence</span></div>${data.entries.length?data.entries.map((x,i)=>`<a class="leader-row" href="/profile/${encodeURIComponent(x.handle)}" data-link><span class="rank">#${i+1}</span><span class="leader-name">${h(x.handle)}</span><span class="leader-score">${h(x.rating??'—')}</span><span class="muted">${type==='challenge'?`${x.ratedTasks} tasks`:`${x.episodes} episodes`}</span></a>`).join(''):'<div class="empty">The public beta ladder is ready for its first eligible builders.</div>'}</div></div>`)}
async function profile(handle){loading();const {profile:p}=await request(`/api/profile/${encodeURIComponent(handle)}`);const rating=p.challenge.rating??p.workflow?.rating??'—';page(`${p.handle}'s profile`, `<div class="shell"><section class="profile-hero"><div class="page-head"><div class="eyebrow">Public builder profile</div><h1>@${h(p.handle)}</h1><p>Two evidence lanes tell the honest story: controlled challenge results and provisional real-work signals.</p></div><div class="profile-rating"><div><strong>${h(rating)}</strong><span>${p.challenge.rating?'Challenge rating':'Workflow score'}</span></div></div></section><div class="path-grid"><article class="card"><div class="challenge-meta"><span>Assessed challenges</span><span>${p.challenge.eligible?'Ranked':'Building evidence'}</span></div><h2>${p.challenge.rating??'Not established'}</h2><p>${p.challenge.ratedTasks} rated tasks · ${p.challenge.completed} completed attempts</p></article><article class="card"><div class="challenge-meta"><span>Imported workflow</span><span>Provisional</span></div><h2>${p.workflow?.rating??'Not connected'}</h2><p>${p.workflow?`${p.workflow.episodes} episodes · ${h(p.workflow.agent)}`:'No public local-work report yet.'}</p></article></div></div>`)}

async function settings(){if(!session)return navigate('/login');session=await request('/api/me');page('Settings',`<div class="shell"><header class="page-head"><div class="eyebrow">Account controls</div><h1>Settings.</h1><p>Your data stays private until you choose otherwise. Deleting your account removes its attempts, messages, reports, and scores.</p></header><div class="dashboard-grid"><section class="card"><h2>Public profile</h2><p class="muted">${session.user.isPublic?'Your profile and eligible scores are visible on the public leaderboard.':'Your account, attempts, and reports are private.'}</p><button class="button ${session.user.isPublic?'ghost':''}" data-action="visibility" data-value="${!session.user.isPublic}">${session.user.isPublic?'Make profile private':'Publish my profile'}</button></section><section class="card"><h2>Delete account</h2><p class="muted">This permanently removes your beta data.</p><form id="delete-form" class="form"><div class="field"><label>Type ${h(session.user.handle)} to confirm</label><input name="confirmHandle" autocomplete="off"></div><button class="button danger" type="submit">Delete my account</button></form></section></div></div>`)}
function privacy(){page('Privacy',`<div class="shell"><header class="page-head"><div class="eyebrow">Local first by design</div><h1>Your code is yours.</h1></header><article class="privacy-copy"><h2>What stays on your machine</h2><p>The VibeScore MCP analyzes only project and session files you explicitly select. Prompt text, source code, commands, file paths, and filenames are reduced locally and are not included in publishable reports.</p><h2>What you can publish</h2><p>Publishing is opt-in. The MCP first shows the exact numeric bundle and its SHA-256 digest. Upload requires a second call with that exact digest and explicit confirmation.</p><h2>What the server stores</h2><p>Accounts, challenge attempts, assistant messages, numeric reports, score history, and feedback. Credentials are stored as one-way hashes. Profiles are private by default.</p><h2>What the scores mean</h2><p>Imported workflow scores are provisional self-reported evidence. Controlled challenge ratings come from server-run tests, but are not identity-proctored hiring credentials. We keep them separate.</p><h2>Your controls</h2><p>You can make your profile private or delete the account and its associated beta data from Settings.</p></article></div>`)}
function hokie(){page('VibeScore for Hokies',`<div class="shell"><header class="page-head"><div class="eyebrow">HokieAI Side Kick</div><h1>What kind of<br>AI builder are you?</h1><p>Take a two-minute readiness check, then get one focused practice recommendation. This launch experience connects Virginia Tech students to the complete VibeScore career-readiness path.</p></header><section class="card hokie-banner" id="hokie-quiz"><div class="challenge-meta"><span>Question 1 of 3</span><span>Career readiness check</span></div><h2>When your coding assistant produces a plausible solution, what do you do next?</h2><div class="quiz-options"><button class="quiz-option" data-quiz="0" data-points="0">Ship it while the context is fresh</button><button class="quiz-option" data-quiz="0" data-points="1">Read the main path and fix anything obvious</button><button class="quiz-option" data-quiz="0" data-points="2">Run focused tests, inspect edge cases, and review the diff</button></div></section><section class="section"><div class="eyebrow">GoDaddy ANS trust explorer</div><h2 class="section-title">Find the agents behind the name.</h2><p class="section-intro">Search the Agent Name Service directory, inspect one registered identity, and see which trust signals exist before choosing a service.</p><form class="ans-search" id="ans-search"><input name="query" aria-label="Search registered AI agents" minlength="2" maxlength="128" placeholder="Try career, campus, or MCP" required><button class="button" type="submit">Discover agents</button></form><div id="ans-results" class="ans-results"><div class="empty">ANS discovery is ready when event credentials are configured.</div></div></section></div>`)}

function renderAnsAgents(data){const box=document.querySelector('#ans-results');box.innerHTML=data.agents.length?`<div class="ans-grid">${data.agents.map(a=>`<article class="card ans-card"><div class="challenge-meta"><span>${h(a.protocol||'Agent')}</span><span>${h(a.status)}</span></div><h3>${h(a.displayName)}</h3><p>${h(a.description||'Registered agent')}</p><div class="trust-row"><span>${a.trustScore===null?'Trust pending':`Trust ${h(a.trustScore)}`}</span><span>${h(a.ansName||a.host||'Registry identity')}</span></div><button class="button ghost small" data-ans-id="${h(a.agentId)}">Verify registry signals →</button></article>`).join('')}</div>`:'<div class="empty">No active agents matched that search.</div>'}
function renderAnsTrust(data){const box=document.querySelector('#ans-results');box.insertAdjacentHTML('afterbegin',`<article class="card ans-trust"><div><div class="eyebrow">Registry verification</div><h3>${h(data.displayName)}</h3><p>${h(data.ansName||data.host||data.agentId)}</p></div><div class="profile-rating"><div><strong>${data.trustScore===null?'—':h(data.trustScore)}</strong><span>ANS trust score</span></div></div><dl><div><dt>Lifecycle</dt><dd>${h(data.status)}</dd></div><div><dt>Signal coverage</dt><dd>${data.coverageRatio===null?'Not published':`${Math.round(data.coverageRatio*100)}%`}</dd></div><div><dt>Identity</dt><dd>${data.trustVector.identity??'—'}</dd></div><div><dt>Integrity</dt><dd>${data.trustVector.integrity??'—'}</dd></div></dl><p class="muted">Verified from the ANS registry response. Missing signals: ${h(data.missingSignals.join(', ')||'none reported')}.</p></article>`)}
const quiz=[{q:'When a coding agent fails twice on the same issue, what is your next move?',a:[['Ask it to try again',0],['Switch models immediately',1],['Stop, summarize evidence, and change the hypothesis',2]]},{q:'What makes a strong first prompt?',a:[['A detailed list of technologies',1],['The user outcome, constraints, evidence, and success checks',2],['A short command so the model has freedom',0]]}];
function quizStep(index,points){const box=document.querySelector('#hokie-quiz');if(index>=quiz.length){const type=points>=5?'The Systems Builder':points>=3?'The Fast Iteration Builder':'The Instinctive Builder',skill=points>=5?'efficiency':points>=3?'verification':'framing';box.innerHTML=`<div class="eyebrow">Your builder archetype</div><h2>${type}</h2><p>You have useful instincts. Your recommended starting focus is <b>${skill}</b>—one controlled drill will make the next step concrete.</p><div class="hero-actions"><a class="button coral" href="/practice" data-link>Start my recommended practice →</a><a class="button ghost" href="/join" data-link>Save a public profile</a></div>`;return}const item=quiz[index];box.innerHTML=`<div class="challenge-meta"><span>Question ${index+2} of 3</span><span>Career readiness check</span></div><h2>${h(item.q)}</h2><div class="quiz-options">${item.a.map(([label,p])=>`<button class="quiz-option" data-quiz="${index+1}" data-total="${points+Number(p)}">${h(label)}</button>`).join('')}</div>`}
function notFound(){page('Not found','<div class="error-page"><h1>404</h1><p class="muted">That page moved, or never existed.</p><a class="button" href="/" data-link>Back home</a></div>')}

async function render(){clearInterval(timerId);const path=location.pathname;try{if(path==='/')return home();if(path==='/practice')return practice();if(path==='/login'||path==='/join'||path==='/recover')return authPage(path.slice(1));if(path==='/dashboard')return dashboard();if(path==='/leaderboard')return leaderboard();if(path==='/settings')return settings();if(path==='/privacy')return privacy();if(path==='/hokie')return hokie();if(path.startsWith('/challenge/'))return challengeDetail(decodeURIComponent(path.slice(11)));if(path.startsWith('/attempt/'))return attemptPage(decodeURIComponent(path.slice(9)));if(path.startsWith('/profile/'))return profile(decodeURIComponent(path.slice(9)));return notFound()}catch(error){page('Something went wrong',`<div class="error-page"><h1>We hit a snag.</h1><p class="muted">${h(error.message)}</p><button class="button" data-action="retry">Try again</button></div>`)}finally{document.querySelectorAll('.nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===path))}}

document.addEventListener('click',async event=>{const link=event.target.closest('[data-link]');if(link&&link.origin===location.origin){event.preventDefault();navigate(link.getAttribute('href'));return}const target=event.target.closest('button');if(!target)return;try{
  if(target.dataset.filter)return practice(target.dataset.filter);
  if(target.dataset.board)return leaderboard(target.dataset.board);
  if(target.dataset.start){if(!session)return navigate('/login');target.disabled=true;const data=await request(`/api/challenges/${encodeURIComponent(target.dataset.start)}/start`,{method:'POST',body:JSON.stringify({mode:target.dataset.mode})});navigate(`/attempt/${data.attempt.id}`)}
  if(target.dataset.action==='logout'){await request('/api/logout',{method:'POST'});session=null;updateNav();navigate('/')}
  if(target.dataset.action==='copy-recovery'){await navigator.clipboard.writeText(target.dataset.code);toast('Recovery code copied')}
  if(target.dataset.action==='retry')render();
  if(target.dataset.action==='save-draft'){const id=location.pathname.slice(9);await saveAttempt(id,{answer:document.querySelector('#answer')?.value,code:document.querySelector('#code-editor')?.value})}
  if(target.dataset.action==='run-code'){target.disabled=true;const id=location.pathname.slice(9),data=await request(`/api/attempts/${id}/run`,{method:'POST',body:JSON.stringify({code:document.querySelector('#code-editor').value})});document.querySelector('#run-results').innerHTML=`<h3>Visible tests</h3>${data.results.map(x=>`<div class="test-row"><span>${h(x.id)}</span><b class="${x.passed?'pass':'fail'}">${x.passed?'Passed':'Failed'}</b></div>`).join('')}`;target.disabled=false}
  if(target.dataset.action==='submit-code'){if(!confirm('Submit this solution? A rated first attempt cannot be repeated for rating credit.'))return;target.disabled=true;const id=location.pathname.slice(9),data=await request(`/api/attempts/${id}/submit`,{method:'POST',body:JSON.stringify({code:document.querySelector('#code-editor').value,reflection:'Submitted from the coding workspace.'})});toast(`Submitted: ${data.result.totalScore}%`);render()}
  if(target.dataset.action==='visibility'){const data=await request('/api/me',{method:'PATCH',body:JSON.stringify({isPublic:target.dataset.value==='true'})});session.user=data.user;toast(data.user.isPublic?'Profile published':'Profile is private');settings()}
  if(target.dataset.ansId){target.disabled=true;const data=await request(`/api/ans/agents/${encodeURIComponent(target.dataset.ansId)}`);renderAnsTrust(data);target.disabled=false}
  if(target.dataset.quiz!==undefined){quizStep(Number(target.dataset.quiz),Number(target.dataset.total??target.dataset.points??0))}
}catch(error){target.disabled=false;toast(error.message,true)}});

document.addEventListener('submit',async event=>{event.preventDefault();const form=event.target;try{
  if(form.id==='auth-form'){const values=Object.fromEntries(new FormData(form));const kind=form.dataset.kind,path=kind==='join'?'/api/register':kind==='recover'?'/api/recover':'/api/login';const data=await request(path,{method:'POST',body:JSON.stringify(values)});await loadSession();if(data.recoveryCode)return showRecovery(data.recoveryCode);navigate('/dashboard')}
  if(form.id==='drill-form'){const id=location.pathname.slice(9),answer=form.answer.value;await saveAttempt(id,{answer},false);await request(`/api/attempts/${id}/submit`,{method:'POST',body:JSON.stringify({answer})});render()}
  if(form.id==='chat-form'){const input=form.message,message=input.value.trim();if(!message)return;input.value='';const chat=document.querySelector('#chat');chat.insertAdjacentHTML('beforeend',`<div class="message user">${h(message)}</div>`);const id=location.pathname.slice(9),data=await request(`/api/attempts/${id}/chat`,{method:'POST',body:JSON.stringify({message})});chat.insertAdjacentHTML('beforeend',`<div class="message assistant">${h(data.message)}</div>`);chat.scrollTop=chat.scrollHeight}
  if(form.id==='ans-search'){const query=form.query.value.trim(),box=document.querySelector('#ans-results');box.innerHTML='<div class="route-loading"><span></span><p>Searching the ANS registry…</p></div>';renderAnsAgents(await request(`/api/ans/search?q=${encodeURIComponent(query)}`))}
  if(form.id==='delete-form'){const confirmHandle=form.confirmHandle.value;if(!confirm('Permanently delete this account and all beta data?'))return;await request('/api/me',{method:'DELETE',body:JSON.stringify({confirmHandle})});session=null;updateNav();navigate('/')}
}catch(error){toast(error.message,true)}});
window.addEventListener('popstate',render);
await loadSession();render();
